### ISSUE TITLE
Should I expect k-rail to stop tiller being installed?

### ISSUE THREAD

**Issue by drnic** [cruise-automation/k-rail#4]
I installed k-rail, then installed tiller, and no errors stopped me. What is the scope of tiller installation being prevented? https://github.com/cruise-automation/k-rail#no-helm-tiller

My script that installs k-rail first, then tiller via [1]:

```
--> waiting for k-rail to be active...
pod/k-rail-6bfd6fd575-7w2s6 condition met
pod/k-rail-6bfd6fd575-cm822 condition met
pod/k-rail-6bfd6fd575-jl9w7 condition met

Install/upgrade Tiller Server for Helm
Installing helm into current Kuberenetes context...
serviceaccount/helm created
clusterrolebinding.rbac.authorization.k8s.io/helm created
Creating certificates...
$HELM_HOME has been configured at /Users/drnic/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.
Installing helm client certificates...
Tiller is ready, testing connection, and certificates:
  working!
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "starkandwayne" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
```

Does k-rail allow my tiller because it is secured by TLS? [1]

[1] https://github.com/starkandwayne/helm-tiller-manager

**Comment by dustin-decker** [comment]
The `No Tiller` policy is not very robust, because there isn't a great way to detect Tiller. We created that policy not as a strong security control, but a reminder to our engineers that Tiller should not be used, and to seek alternate methods that we provide. All the policy does is check for the[ substring `/tiller` in the image name](https://github.com/cruise-automation/k-rail/blob/master/policies/pod/no_tiller.go#L44), which matches what the official docs specify for Helm 2: https://helm.sh/docs/using_helm/#upgrading-tiller
It likely isn't triggering for you because your image name does not contain `/tiller`.

On a related note, the `No Docker Sock` policy is also not very robust because it blocks hostPath mounts with `/var/run/docker.sock` but not one with `/var/run` or `/var`. It is more useful for analyzing usage of that mount and as a step towards blocking all hostPath mounts. It is recommended that you apply the `No Bind Mount` policy  (no hostPath mounts) because it does block all paths.

**Comment by dustin-decker** [comment]
I've updated the readme with notes on the aforementioned policies.

**Comment by drnic** [comment]
Ok, I'll close now.

Thanks for all the extra info.
